import type { TimeEntry, TimeEntryCorrection, TimeEntryType } from "./types";
export type ClockPhase="out"|"in"|"break";
export interface TimeSummary {phase:ClockPhase;expected:TimeEntryType;clockIn:string|null;clockOut:string|null;breaks:Array<{start:string;end:string|null}>;workedSeconds:number;entries:TimeEntry[]}
const zone="America/Los_Angeles";
export const pacificDate=(date:Date|string)=>new Intl.DateTimeFormat("en-CA",{timeZone:zone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(date));
export const formatPacificTime=(iso:string)=>new Intl.DateTimeFormat("en-US",{timeZone:zone,hour:"numeric",minute:"2-digit"}).format(new Date(iso));
export function formatHoursDuration(hours:number):string{const totalMinutes=Math.round(Math.max(0,Number.isFinite(hours)?hours:0)*60);const wholeHours=Math.floor(totalMinutes/60);const minutes=totalMinutes%60;if(wholeHours&&minutes)return `${wholeHours}h ${minutes}m`;if(wholeHours)return `${wholeHours}h`;return minutes?`${minutes}m`:"0h";}
export function applyTimeCorrections(entries:TimeEntry[],corrections:TimeEntryCorrection[]):TimeEntry[]{const replaced=new Set(corrections.map(c=>c.originalEntryId).filter(Boolean));const projected=entries.filter(e=>!replaced.has(e.id));for(const c of corrections){projected.push({id:`correction:${c.id}`,userId:c.userId,type:c.replacementType,at:c.replacementAt,correctedByRequestId:c.requestId,originalEntryId:c.originalEntryId});}return projected.sort((a,b)=>a.at.localeCompare(b.at));}
export function summarizeTime(userId:string,all:TimeEntry[],now=new Date()):TimeSummary{const day=pacificDate(now);const entries=all.filter(e=>e.userId===userId&&pacificDate(e.at)===day).sort((a,b)=>a.at.localeCompare(b.at));let phase:ClockPhase="out",expected:TimeEntryType="clock_in",clockIn:string|null=null,clockOut:string|null=null,activeStart:number|null=null,worked=0;const breaks:Array<{start:string;end:string|null}>=[];for(const entry of entries){const at=new Date(entry.at).getTime();if(entry.type==="clock_in"){phase="in";expected="break_start";clockIn=entry.at;activeStart=at;}else if(entry.type==="break_start"&&phase==="in"){if(activeStart!==null)worked+=Math.max(0,at-activeStart);phase="break";expected="break_end";activeStart=null;breaks.push({start:entry.at,end:null});}else if(entry.type==="break_end"&&phase==="break"){phase="in";expected="clock_out";activeStart=at;if(breaks.length)breaks[breaks.length-1].end=entry.at;}else if(entry.type==="clock_out"&&phase==="in"){if(activeStart!==null)worked+=Math.max(0,at-activeStart);phase="out";expected="clock_in";activeStart=null;clockOut=entry.at;}}
if(phase==="in"&&activeStart!==null)worked+=Math.max(0,now.getTime()-activeStart);return {phase,expected,clockIn,clockOut,breaks,workedSeconds:Math.floor(worked/1000),entries};}
