import type { AppNotification, CompanySettings, Customer, Dumpster, InvoiceRecord, Job, JobActivity, JobNote, MessageChannel, PretripSubmission, PretripTemplate, SopDocument, TeamMessage, TimeEntry, TimeEntryCorrection, TimeRequest, Truck, User } from "@/lib/types";
import type { AbsenceRow, CompanySettingsRow, CorrectionRow, CustomerRow, DumpsterRow, InvoiceRow, JobActivityRow, JobEventRow, JobNoteRow, JobPhotoRow, JobRow, MessageChannelRow, MessageRow, NotificationRow, PretripSubmissionRow, PretripTemplateRow, SopDocumentRow, TimeEntryRow, TimeRequestRow, TruckRow, UserRow } from "./database.types";

export function mapUser(row:UserRow):User { return { id:row.id,employeeId:row.employee_id,fullName:row.full_name,email:row.email,phone:row.phone,role:row.role,accessRole:row.access_role,permissionOverrides:(row.permission_overrides??{}) as User["permissionOverrides"],status:row.status,initials:row.initials,ptoBalanceHours:row.pto_balance_hours??undefined,weeklyHours:row.weekly_hours??undefined }; }
export function mapCustomer(row:CustomerRow,activeJobs=0):Customer { return { id:row.id,name:row.name,phone:row.phone,email:row.email,address:row.address,activeJobs,group:row.customer_group??undefined }; }
export function mapTruck(row:TruckRow):Truck { return { id:row.id,number:row.number,type:row.type,status:row.status,licensePlate:row.license_plate,registrationDueDate:row.registration_due_date??"",mileage:row.mileage,lastPmDate:row.last_pm_date??"",lastPmMileage:row.last_pm_mileage,nextPmDate:row.next_pm_date??"",nextPmMileage:row.next_pm_mileage,make:row.make,model:row.model,vin:row.vin,assignedDriverId:row.assigned_driver_id,currentJobId:row.current_job_id,notes:row.notes,airTagId:row.air_tag_id,gpsSource:row.gps_source??undefined,lastKnownLocation:row.last_known_location??undefined,lastSeenAt:row.last_seen_at??undefined }; }
export function mapDumpster(row:DumpsterRow):Dumpster { return { id:row.id,code:row.code,size:row.size,status:row.status,type:row.type,currentCustomerId:row.current_customer_id,currentLocation:row.current_location,currentJobId:row.current_job_id,airTagId:row.air_tag_id,notes:row.notes }; }
export function mapJob(row:JobRow,photos:JobPhotoRow[]=[],events:JobEventRow[]=[]):Job { return { id:row.id,reference:row.reference,customerId:row.customer_id,address:row.address,phone:row.phone,serviceType:row.service_type as Job["serviceType"],dumpsterSize:row.dumpster_size as Job["dumpsterSize"],assignedDriverId:row.assigned_driver_id,assignedTruckId:row.assigned_truck_id,assignedDumpsterId:row.assigned_dumpster_id,scheduledFor:row.scheduled_for,status:row.status,notes:row.notes,trafficInstructions:row.traffic_instructions??undefined,photos:photos.filter(p=>p.job_id===row.id).map(p=>({id:p.id,jobId:p.job_id,url:p.url,uploadedById:p.uploaded_by_id,createdAt:p.created_at})),timeline:events.filter(e=>e.job_id===row.id).map(e=>({type:e.event_type as Job["timeline"][number]["type"],at:e.occurred_at})) }; }
export function mapNotification(row:NotificationRow):AppNotification { return {id:row.id,recipientUserId:row.recipient_user_id,sourceRole:row.source_role,category:row.category as AppNotification["category"],title:row.title,body:row.body,relatedJobId:row.related_job_id,createdAt:row.created_at,requiresAcknowledgement:row.requires_acknowledgement,acknowledgedAt:row.acknowledged_at}; }
export function mapActivity(row:JobActivityRow):JobActivity { return {id:row.id,jobId:row.job_id,actorId:row.actor_id,actorName:row.actor_name,type:row.activity_type as JobActivity["type"],body:row.body,createdAt:row.created_at,dispatchNotified:row.dispatch_notified}; }
export function mapJobNote(row:JobNoteRow,authorName="Employee"):JobNote { return {id:row.id,jobId:row.job_id,authorId:row.author_id,authorName,body:row.body,createdAt:row.created_at}; }
export function mapTimeEntry(row:TimeEntryRow):TimeEntry { return {id:row.id,userId:row.user_id,type:row.entry_type,at:row.occurred_at}; }
export function mapTimeCorrection(row:CorrectionRow):TimeEntryCorrection { return {id:row.id,requestId:row.request_id,originalEntryId:row.original_entry_id,userId:row.user_id,replacementType:row.replacement_type,replacementAt:row.replacement_at}; }
export function mapTimeRequest(row:TimeRequestRow):TimeRequest { return {id:row.id,userId:row.user_id,kind:row.kind,status:row.status,requestedFor:row.requested_for,hours:row.hours,reason:row.reason,targetEntryId:row.target_entry_id,requestedEntryType:row.requested_entry_type,requestedAt:row.requested_at}; }
export function mapAbsence(row:AbsenceRow){return {id:row.id,userId:row.user_id,date:row.event_date,type:row.absence_type,status:row.status,note:row.note} as const;}
export const mapInvoice=(row:InvoiceRow):InvoiceRecord=>({id:row.id,invoiceNumber:row.invoice_number,customerId:row.customer_id,jobId:row.job_id,amountCents:Number(row.amount_cents),status:row.status,dueDate:row.due_date,notes:row.notes,sentAt:row.sent_at,paidAt:row.paid_at,closedAt:row.closed_at,createdAt:row.created_at});
export const mapMessageChannel=(row:MessageChannelRow):MessageChannel=>({id:row.id,name:row.name,kind:row.kind,createdAt:row.created_at});
export const mapTeamMessage=(row:MessageRow,read=false):TeamMessage=>({id:row.id,channelId:row.channel_id,senderId:row.sender_id,body:row.body,createdAt:row.created_at,read});
export const mapPretripTemplate=(row:PretripTemplateRow):PretripTemplate=>({id:row.id,title:row.title,version:row.version,isPublished:row.is_published,items:row.items as unknown as PretripTemplate["items"]});
export const mapPretripSubmission=(row:PretripSubmissionRow):PretripSubmission=>({id:row.id,templateId:row.template_id,driverId:row.driver_id,truckId:row.truck_id,mileage:row.mileage,signature:row.signature,results:row.results as PretripSubmission["results"],hasFailures:row.has_failures,submittedAt:row.submitted_at});
export const mapSopDocument=(row:SopDocumentRow,acknowledged=false):SopDocument=>({id:row.id,title:row.title,category:row.category,version:row.version,body:row.body,isPublished:row.is_published,requiredForDrivers:row.required_for_drivers,createdAt:row.created_at,acknowledged});
export const mapCompanySettings=(row:CompanySettingsRow):CompanySettings=>({companyName:row.company_name,address:row.address,phone:row.phone,email:row.email,timeZone:row.time_zone,dateFormat:row.date_format,messageRetentionDays:row.message_retention_days,invoicePrefix:row.invoice_prefix});
