import { expect, test, type Page } from "@playwright/test";
import { createHmac } from "node:crypto";

function totp(secret:string){const alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";const clean=secret.replace(/\s/g,"").toUpperCase().replace(/=+$/,"");let bits="";for(const char of clean)bits+=alphabet.indexOf(char).toString(2).padStart(5,"0");const key=Buffer.from((bits.match(/.{8}/g)??[]).map(byte=>parseInt(byte,2)));const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const digest=createHmac("sha1",key).update(counter).digest();const offset=digest[digest.length-1]&15;return (((digest[offset]&127)<<24|(digest[offset+1]&255)<<16|(digest[offset+2]&255)<<8|(digest[offset+3]&255))%1_000_000).toString().padStart(6,"0");}
async function signIn(page:Page,email:string,password:string,mfaSecret?:string){await page.goto("/login");await page.getByLabel(/email/i).fill(email);await page.getByLabel(/password/i).fill(password);await page.getByRole("button",{name:/sign in/i}).click();if(mfaSecret){await expect(page).toHaveURL(/\/mfa/);await page.getByLabel(/six-digit code/i).fill(totp(mfaSecret));await page.getByRole("button",{name:/verify and continue/i}).click();}}

test.describe("authenticated production journeys",()=>{
 test("administrator completes MFA and reaches every activated office module",async({page})=>{test.skip(!process.env.E2E_ADMIN_EMAIL||!process.env.E2E_ADMIN_PASSWORD||!process.env.E2E_ADMIN_TOTP_SECRET,"Requires approved staging admin identity and TOTP secret");await signIn(page,process.env.E2E_ADMIN_EMAIL!,process.env.E2E_ADMIN_PASSWORD!,process.env.E2E_ADMIN_TOTP_SECRET);await expect(page).toHaveURL(/\/dispatcher\//);for(const [path,heading] of [["/dispatcher/invoices","Invoices"],["/dispatcher/reports","Reports"],["/dispatcher/map","Locations & AirTags"],["/dispatcher/messages","Messages"],["/dispatcher/settings","Settings"]]){await page.goto(path);await expect(page.getByText(heading,{exact:false}).first()).toBeVisible();}await page.goto("/management");await expect(page.getByText("Management Portal")).toBeVisible();});
 test("dispatcher reaches live daily operations",async({page})=>{test.skip(!process.env.E2E_DISPATCHER_EMAIL||!process.env.E2E_DISPATCHER_PASSWORD,"Requires approved staging dispatcher identity");await signIn(page,process.env.E2E_DISPATCHER_EMAIL!,process.env.E2E_DISPATCHER_PASSWORD!);await expect(page).toHaveURL(/\/dispatcher\/dashboard/);await expect(page.getByRole("button",{name:/new job/i})).toBeVisible();await page.goto("/dispatcher/jobs");await expect(page.getByText("Jobs",{exact:true}).first()).toBeVisible();await page.goto("/dispatcher/messages");await expect(page.getByText("Channels")).toBeVisible();});
 test("driver reaches field, time, messages, pre-trip, and SOP workflows",async({page})=>{test.skip(!process.env.E2E_DRIVER_EMAIL||!process.env.E2E_DRIVER_PASSWORD,"Requires approved staging driver identity");await signIn(page,process.env.E2E_DRIVER_EMAIL!,process.env.E2E_DRIVER_PASSWORD!);await expect(page).toHaveURL(/\/driver\/jobs/);await expect(page.getByRole("button",{name:"Upcoming"})).toBeVisible();for(const path of ["/driver/time-clock","/driver/messages","/driver/pre-trip","/driver/sops"]){await page.goto(path);await expect(page.locator("main, header").first()).toBeVisible();}});
 test("inactive employee is rejected",async({page})=>{test.skip(!process.env.E2E_INACTIVE_EMAIL||!process.env.E2E_INACTIVE_PASSWORD,"Requires approved inactive staging identity");await signIn(page,process.env.E2E_INACTIVE_EMAIL!,process.env.E2E_INACTIVE_PASSWORD!);await expect(page).toHaveURL(/\/login/);await expect(page.getByRole("alert")).toContainText(/inactive|not linked/i);});
 test("reduced dispatcher cannot open revoked modules",async({page})=>{test.skip(!process.env.E2E_REDUCED_EMAIL||!process.env.E2E_REDUCED_PASSWORD,"Requires approved reduced-permission identity");await signIn(page,process.env.E2E_REDUCED_EMAIL!,process.env.E2E_REDUCED_PASSWORD!);await page.goto("/dispatcher/customers");await expect(page).not.toHaveURL(/\/dispatcher\/customers/);await expect(page.getByRole("link",{name:"Customers"})).toHaveCount(0);});
});
