"use client";
import * as React from "react";
import { createClient } from "@/lib/supabase/client";
import { mapCompanySettings,mapInvoice,mapMessageChannel,mapPretripSubmission,mapPretripTemplate,mapSopDocument,mapTeamMessage } from "@/lib/supabase/mappers";
import type { CompanySettings,InvoiceRecord,InvoiceStatus,MessageChannel,PretripSubmission,PretripTemplate,SopDocument,TeamMessage } from "@/lib/types";
import type { CompanySettingsRow,InvoiceRow,MessageChannelRow,MessageReadRow,MessageRow,PretripSubmissionRow,PretripTemplateRow,SopAcknowledgementRow,SopDocumentRow } from "@/lib/supabase/database.types";
import { useOperations, type MutationResult } from "./OperationsProvider";

export interface InvoiceInput{invoiceNumber:string;customerId:string;jobId:string|null;amountCents:number;status:InvoiceStatus;dueDate:string;notes:string}
type State={invoices:InvoiceRecord[];channels:MessageChannel[];messages:TeamMessage[];messageRecipients:{id:string;fullName:string}[];pretripTemplates:PretripTemplate[];pretripSubmissions:PretripSubmission[];sops:SopDocument[];settings:CompanySettings|null};
type Value=State&{loading:boolean;refresh:()=>Promise<void>;saveInvoice:(input:InvoiceInput,id?:string)=>Promise<MutationResult<void>>;sendMessage:(channelId:string,body:string)=>Promise<MutationResult<void>>;createDirectChannel:(userId:string)=>Promise<MutationResult<string>>;markChannelRead:(channelId:string)=>Promise<MutationResult<void>>;submitPretrip:(input:{templateId:string;truckId:string;mileage:number;signature:string;results:Record<string,"pass"|"fail">})=>Promise<MutationResult<void>>;acknowledgeSop:(sopId:string)=>Promise<MutationResult<void>>;saveSettings:(value:CompanySettings)=>Promise<MutationResult<void>>;publishSop:(input:{title:string;category:string;body:string;requiredForDrivers:boolean})=>Promise<MutationResult<void>>;publishPretripTemplate:(input:{title:string;items:string[]})=>Promise<MutationResult<void>>};
const Context=React.createContext<Value|null>(null);const initial:State={invoices:[],channels:[],messages:[],messageRecipients:[],pretripTemplates:[],pretripSubmissions:[],sops:[],settings:null};
const fail=(e:unknown):MutationResult<never>=>({ok:false,error:{code:(e as {code?:string})?.code??"expanded_operation_failed",message:(e as {message?:string})?.message??"The operation could not be completed."}});

export function ExpandedOperationsProvider({children}:{children:React.ReactNode}){
 const {currentUser,canMutate}=useOperations();const [loading,setLoading]=React.useState(true);const [data,setData]=React.useState<State>(initial);
 const refresh=React.useCallback(async()=>{if(!currentUser){setData(initial);setLoading(false);return;}setLoading(true);const db=createClient();const results=await Promise.all([db.from("invoices").select("*").order("due_date"),db.rpc("list_message_channels"),db.from("messages").select("*").order("created_at"),db.from("message_reads").select("*"),db.from("pretrip_templates").select("*").order("version",{ascending:false}),db.from("pretrip_submissions").select("*").order("submitted_at",{ascending:false}),db.from("sop_documents").select("*").order("created_at",{ascending:false}),db.from("sop_acknowledgements").select("*"),db.from("company_settings").select("*").maybeSingle(),db.rpc("list_message_recipients")]);const error=results.find(r=>r.error)?.error;if(error){setLoading(false);return;}const [ir,cr,mr,rr,ptr,psr,sr,sar,csr,recipients]=results;const reads=new Set((rr.data as MessageReadRow[]).filter(r=>r.user_id===currentUser.id).map(r=>r.message_id));const acks=new Set((sar.data as SopAcknowledgementRow[]).filter(r=>r.user_id===currentUser.id).map(r=>r.sop_id));setData({invoices:(ir.data as InvoiceRow[]).map(mapInvoice),channels:(cr.data as MessageChannelRow[]).map(mapMessageChannel),messages:(mr.data as MessageRow[]).map(r=>mapTeamMessage(r,reads.has(r.id))),messageRecipients:((recipients.data??[]) as {id:string;full_name:string}[]).map(r=>({id:r.id,fullName:r.full_name})),pretripTemplates:(ptr.data as PretripTemplateRow[]).map(mapPretripTemplate),pretripSubmissions:(psr.data as PretripSubmissionRow[]).map(mapPretripSubmission),sops:(sr.data as SopDocumentRow[]).map(r=>mapSopDocument(r,acks.has(r.id))),settings:csr.data?mapCompanySettings(csr.data as CompanySettingsRow):null});setLoading(false);},[currentUser]);
 React.useEffect(()=>{void refresh();if(!currentUser)return;const db=createClient();const channel=db.channel("expanded-operations");for(const table of ["invoices","message_channels","message_channel_members","messages","message_reads","pretrip_templates","pretrip_submissions","sop_documents","sop_acknowledgements","company_settings"] as const)channel.on("postgres_changes",{event:"*",schema:"public",table},()=>void refresh());channel.subscribe();return()=>{void db.removeChannel(channel);};},[currentUser,refresh]);
 const run=React.useCallback(async(work:()=>PromiseLike<{error:unknown}>)=>{if(!canMutate)return fail({message:"Changes are disabled until the live connection is restored."});try{const r=await work();if(r.error)throw r.error;await refresh();return {ok:true,data:undefined} as MutationResult<void>;}catch(e){return fail(e);}},[canMutate,refresh]);
 const value=React.useMemo<Value>(()=>({loading,...data,refresh,
  saveInvoice:(input,id)=>run(()=>id?createClient().from("invoices").update({invoice_number:input.invoiceNumber.trim(),customer_id:input.customerId,job_id:input.jobId,amount_cents:input.amountCents,status:input.status,due_date:input.dueDate,notes:input.notes.trim()}).eq("id",id):createClient().from("invoices").insert({invoice_number:input.invoiceNumber.trim(),customer_id:input.customerId,job_id:input.jobId,amount_cents:input.amountCents,status:input.status,due_date:input.dueDate,notes:input.notes.trim(),created_by_id:currentUser?.id})),
  sendMessage:(channelId,body)=>run(()=>createClient().from("messages").insert({channel_id:channelId,sender_id:currentUser?.id,body:body.trim()})),
  createDirectChannel:async userId=>{if(!canMutate)return fail({message:"Changes are disabled until the live connection is restored."});try{const r=await createClient().rpc("create_direct_message_channel",{other_user_id:userId});if(r.error)throw r.error;await refresh();return {ok:true,data:r.data};}catch(e){return fail(e);}},
  markChannelRead:channelId=>{const unread=data.messages.filter(m=>m.channelId===channelId&&!m.read&&m.senderId!==currentUser?.id).map(m=>({message_id:m.id,user_id:currentUser?.id}));if(!unread.length)return Promise.resolve({ok:true,data:undefined});return run(()=>createClient().from("message_reads").upsert(unread));},
  submitPretrip:input=>run(async()=>{if(!currentUser)return {error:{message:"Sign in required"}};const hasFailures=Object.values(input.results).includes("fail");const r=await createClient().from("pretrip_submissions").insert({template_id:input.templateId,driver_id:currentUser.id,truck_id:input.truckId,mileage:input.mileage,signature:input.signature.trim(),results:input.results,has_failures:hasFailures});return r;}),
  acknowledgeSop:sopId=>run(()=>createClient().from("sop_acknowledgements").upsert({sop_id:sopId,user_id:currentUser?.id})),
  saveSettings:settings=>run(()=>createClient().rpc("save_company_settings",{company_name:settings.companyName,company_address:settings.address,company_phone:settings.phone,company_email:settings.email,company_time_zone:settings.timeZone,company_date_format:settings.dateFormat,retention_days:settings.messageRetentionDays,invoice_prefix:settings.invoicePrefix})),
  publishSop:input=>run(()=>createClient().rpc("publish_sop_document",{sop_title:input.title,sop_category:input.category,sop_body:input.body,required_for_drivers:input.requiredForDrivers})),
  publishPretripTemplate:input=>run(()=>createClient().rpc("publish_pretrip_template",{template_title:input.title,item_labels:input.items}))
 }),[loading,data,refresh,run,currentUser,canMutate]);return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useExpandedOperations(){const value=React.useContext(Context);if(!value)throw new Error("useExpandedOperations must be used inside ExpandedOperationsProvider");return value;}
