"use client";

import * as React from "react";
import { createClient } from "@/lib/supabase/client";
import { mapAbsence,mapActivity,mapCustomer,mapDumpster,mapJob,mapJobNote,mapNotification,mapTimeCorrection,mapTimeEntry,mapTimeRequest,mapTruck,mapUser } from "@/lib/supabase/mappers";
import { applyTimeCorrections } from "@/lib/time-clock";
import type { AccessRole,AbsenceEvent,AppNotification,Customer,Dumpster,DumpsterSize,Job,JobActivity,JobNote,JobStatus,PermissionKey,ServiceType,TimeEntry,TimeEntryCorrection,TimeEntryType,TimeRequest,Truck,User } from "@/lib/types";
import type { CorrectionRow,CustomerRow,DumpsterRow,JobActivityRow,JobEventRow,JobNoteRow,JobPhotoRow,JobRow,NotificationRow,TimeEntryRow,TimeRequestRow,TruckRow,UserRow,AbsenceRow } from "@/lib/supabase/database.types";

export type ConnectionState="loading"|"ready"|"stale"|"offline"|"unauthorized"|"error";
export type MutationResult<T>={ok:true;data:T}|{ok:false;error:{code:string;message:string}};
interface State {jobs:Job[];notifications:AppNotification[];activities:JobActivity[];users:User[];customers:Customer[];trucks:Truck[];dumpsters:Dumpster[];jobNotes:JobNote[];timeEntries:TimeEntry[];timeEntryCorrections:TimeEntryCorrection[];timeRequests:TimeRequest[];absenceEvents:AbsenceEvent[]}
const emptyState:State={jobs:[],notifications:[],activities:[],users:[],customers:[],trucks:[],dumpsters:[],jobNotes:[],timeEntries:[],timeEntryCorrections:[],timeRequests:[],absenceEvents:[]};
export interface CreateJobInput {customerId:string;address:string;phone:string;serviceType:ServiceType;dumpsterSize:DumpsterSize;assignedDriverId:string|null;assignedTruckId:string|null;assignedDumpsterId:string|null;scheduledFor:string;notes:string;trafficInstructions:string}
export interface CustomerInput {name:string;phone:string;email:string;address:string;group?:Customer["group"]}
export interface TruckInput {number:string;type:string;status:Truck["status"];licensePlate:string;assignedDriverId:string|null;notes:string}
export interface DumpsterInput {code:string;size:Dumpster["size"];status:Dumpster["status"];type:string;airTagId:string|null;currentLocation:string;notes:string}
export interface TimeRequestInput {kind:"edit_time"|"pto";requestedFor:string;hours:number;reason:string;targetEntryId?:string|null;requestedEntryType?:TimeEntryType|null;requestedAt?:string|null}

interface Value extends State {hydrated:boolean;connected:boolean;connectionState:ConnectionState;connectionMessage:string|null;canMutate:boolean;currentUser:User|null;refresh:()=>Promise<void>;createJob:(input:CreateJobInput)=>Promise<MutationResult<Job>>;updateJobStatus:(id:string,status:JobStatus)=>Promise<MutationResult<void>>;completeJobAsDispatcher:(id:string,reason?:string)=>Promise<MutationResult<Job>>;cancelJob:(id:string,reason:string)=>Promise<MutationResult<Job>>;logDryRun:(id:string,reason:string)=>Promise<MutationResult<void>>;assignDriver:(jobId:string,driverId:string)=>Promise<MutationResult<Job>>;acknowledgeNotification:(id:string)=>Promise<MutationResult<void>>;acknowledgeAll:(recipient:string)=>Promise<MutationResult<void>>;notificationsFor:(recipient:string)=>AppNotification[];setUserAccessRole:(id:string,role:AccessRole)=>Promise<MutationResult<void>>;setPermissionOverride:(id:string,key:PermissionKey,value:boolean)=>Promise<MutationResult<void>>;resetPermissionOverrides:(id:string)=>Promise<MutationResult<void>>;recordTimeEntry:(type:TimeEntryType)=>Promise<MutationResult<TimeEntry>>;createTimeRequest:(input:TimeRequestInput)=>Promise<MutationResult<void>>;reviewTimeRequest:(id:string,decision:"approved"|"denied")=>Promise<MutationResult<void>>;uploadJobPhotos:(jobId:string,files:File[])=>Promise<MutationResult<void>>;addJobNote:(jobId:string,body:string)=>Promise<MutationResult<void>>;saveCustomer:(input:CustomerInput,id?:string)=>Promise<MutationResult<void>>;deactivateCustomer:(id:string)=>Promise<MutationResult<void>>;saveTruck:(input:TruckInput,id?:string)=>Promise<MutationResult<void>>;saveDumpster:(input:DumpsterInput,id?:string)=>Promise<MutationResult<void>>}
const Context=React.createContext<Value|null>(null);
interface Value { updateJob:(id:string,input:CreateJobInput)=>Promise<MutationResult<void>> }
function failure(error:unknown):MutationResult<never>{const candidate=error as {code?:string;message?:string};return {ok:false,error:{code:candidate?.code??"unexpected_error",message:candidate?.message??"The operation could not be completed."}};}

export function OperationsProvider({children}:{children:React.ReactNode}){
 const [state,setState]=React.useState<State>(emptyState);const [connectionState,setConnectionState]=React.useState<ConnectionState>("loading");const [connectionMessage,setConnectionMessage]=React.useState<string|null>(null);const [currentUser,setCurrentUser]=React.useState<User|null>(null);const loaded=React.useRef(false);
 const refresh=React.useCallback(async()=>{if(typeof navigator!=="undefined"&&!navigator.onLine){setConnectionState(loaded.current?"stale":"offline");setConnectionMessage("Offline. Operational changes are disabled until connectivity returns.");return;}try{const db=createClient();const auth=await db.auth.getUser();if(auth.error)throw auth.error;if(!auth.data.user){setCurrentUser(null);setConnectionState("unauthorized");setConnectionMessage("Sign in to access operations data.");return;}
  const results=await Promise.all([db.from("jobs").select("*").is("deleted_at",null).order("scheduled_for"),db.from("job_photos").select("*"),db.from("job_events").select("*"),db.from("notifications").select("*").order("created_at",{ascending:false}),db.from("job_activities").select("*").order("created_at",{ascending:false}),db.from("users").select("*").is("deleted_at",null),db.from("customers").select("*").is("deleted_at",null),db.from("trucks").select("*").is("deleted_at",null).order("number"),db.from("dumpsters").select("*").is("deleted_at",null).order("code"),db.from("job_notes").select("*").order("created_at"),db.from("time_entries").select("*").order("occurred_at",{ascending:false}),db.from("time_entry_corrections").select("*").order("created_at",{ascending:false}),db.from("time_requests").select("*").order("created_at",{ascending:false}),db.from("absence_events").select("*").order("event_date")]);
  const err=results.find(r=>r.error)?.error;if(err)throw err;const [jr,pr,er,nr,ar,ur,cr,tr,dr,noter,ter,tcr,reqr,abr]=results;const users=(ur.data as UserRow[]).map(mapUser);const rawPhotos=pr.data as JobPhotoRow[];await Promise.all(rawPhotos.map(async p=>{if(!p.storage_path)return;const signed=await db.storage.from("job-photos").createSignedUrl(p.storage_path,3600);if(signed.data?.signedUrl)p.url=signed.data.signedUrl;}));const jobs=(jr.data as JobRow[]).map(row=>mapJob(row,rawPhotos,er.data as JobEventRow[]));const counts=new Map<string,number>();jobs.filter(j=>j.status!=="complete"&&j.status!=="cancelled").forEach(j=>counts.set(j.customerId,(counts.get(j.customerId)??0)+1));const names=new Map(users.map(u=>[u.id,u.fullName]));const timeEntryCorrections=(tcr.data as CorrectionRow[]).map(mapTimeCorrection);const timeEntries=applyTimeCorrections((ter.data as TimeEntryRow[]).map(mapTimeEntry),timeEntryCorrections);
  setState({jobs,notifications:(nr.data as NotificationRow[]).map(mapNotification),activities:(ar.data as JobActivityRow[]).map(mapActivity),users,customers:(cr.data as CustomerRow[]).map(r=>mapCustomer(r,counts.get(r.id)??0)),trucks:(tr.data as TruckRow[]).map(mapTruck),dumpsters:(dr.data as DumpsterRow[]).map(mapDumpster),jobNotes:(noter.data as JobNoteRow[]).map(r=>mapJobNote(r,names.get(r.author_id))),timeEntries,timeEntryCorrections,timeRequests:(reqr.data as TimeRequestRow[]).map(mapTimeRequest),absenceEvents:(abr.data as AbsenceRow[]).map(mapAbsence)});const profile=(ur.data as UserRow[]).find(u=>u.auth_user_id===auth.data.user.id);if(!profile){setConnectionState("unauthorized");setConnectionMessage("Your account is not linked to an active employee profile.");return;}setCurrentUser(mapUser(profile));loaded.current=true;setConnectionState("ready");setConnectionMessage(null);
 }catch(error){console.error("Operations refresh failed",error);setConnectionState(loaded.current?"stale":"error");setConnectionMessage(loaded.current?"Live data is temporarily unavailable. Showing the last loaded records in read-only mode.":"Operations data could not be loaded.");}},[]);
 React.useEffect(()=>{void refresh();const online=()=>void refresh();const offline=()=>{setConnectionState(loaded.current?"stale":"offline");setConnectionMessage("Offline. Operational changes are disabled until connectivity returns.");};window.addEventListener("online",online);window.addEventListener("offline",offline);const db=createClient();const channel=db.channel("operations-state");for(const table of ["jobs","notifications","job_activities","job_notes","job_photos","time_entries","time_entry_corrections","time_requests","absence_events","users","customers","trucks","dumpsters"] as const)channel.on("postgres_changes",{event:"*",schema:"public",table},()=>void refresh());channel.subscribe();const auth=db.auth.onAuthStateChange(()=>void refresh());return()=>{window.removeEventListener("online",online);window.removeEventListener("offline",offline);auth.data.subscription.unsubscribe();void db.removeChannel(channel);};},[refresh]);
 const canMutate=connectionState==="ready";const guard=React.useCallback(()=>canMutate?null:{ok:false,error:{code:"read_only",message:"Changes are disabled until the live connection is restored."}} as MutationResult<never>,[canMutate]);
 const run=React.useCallback(async<T,>(work:()=>PromiseLike<{data:T|null;error:unknown}>):Promise<MutationResult<T>>=>{const blocked=guard();if(blocked)return blocked;try{const result=await work();if(result.error)throw result.error;await refresh();return {ok:true,data:result.data as T};}catch(error){await refresh();return failure(error);}},[guard,refresh]);
 const value=React.useMemo<Value>(()=>({...state,hydrated:connectionState!=="loading",connected:connectionState==="ready",connectionState,connectionMessage,canMutate,currentUser,refresh,
 createJob:input=>run(async()=>{const r=await createClient().rpc("create_job",{customer_id:input.customerId,job_address:input.address,job_phone:input.phone,service:input.serviceType,container_size:input.dumpsterSize,driver_id:input.assignedDriverId,truck_id:input.assignedTruckId,dumpster_id:input.assignedDumpsterId,schedule_at:new Date(input.scheduledFor).toISOString(),job_notes:input.notes,traffic:input.trafficInstructions});return {data:r.data?mapJob(r.data):null,error:r.error};}),
 updateJob:async(id,input)=>{const r=await run(()=>createClient().rpc("edit_job",{target_job_id:id,customer_id:input.customerId,job_address:input.address,job_phone:input.phone,service:input.serviceType,container_size:input.dumpsterSize,driver_id:input.assignedDriverId,truck_id:input.assignedTruckId,dumpster_id:input.assignedDumpsterId,schedule_at:new Date(input.scheduledFor).toISOString(),job_notes:input.notes,traffic:input.trafficInstructions}));return r.ok?{ok:true,data:undefined}:r;},
 updateJobStatus:async(id,status)=>{const r=await run(()=>createClient().rpc("update_assigned_job_status",{target_job_id:id,next_status:status}));return r.ok?{ok:true,data:undefined}:r;},completeJobAsDispatcher:(id,reason)=>run(async()=>{const r=await createClient().rpc("complete_job_as_dispatch",{target_job_id:id,override_reason:reason??null});return {data:r.data?mapJob(r.data):null,error:r.error};}),cancelJob:(id,reason)=>run(async()=>{const r=await createClient().rpc("cancel_job",{target_job_id:id,cancel_reason:reason});return {data:r.data?mapJob(r.data):null,error:r.error};}),logDryRun:async(id,reason)=>{const r=await run(()=>createClient().rpc("log_assigned_job_dry_run",{target_job_id:id,dry_run_reason:reason}));return r.ok?{ok:true,data:undefined}:r;},assignDriver:(jobId,driverId)=>run(async()=>{const r=await createClient().rpc("assign_job",{target_job_id:jobId,driver_id:driverId});return {data:r.data?mapJob(r.data):null,error:r.error};}),
 acknowledgeNotification:async id=>{const r=await run(()=>createClient().from("notifications").update({acknowledged_at:new Date().toISOString()}).eq("id",id).select().single());return r.ok?{ok:true,data:undefined}:r;},acknowledgeAll:async recipient=>{const r=await run(()=>createClient().from("notifications").update({acknowledged_at:new Date().toISOString()}).eq("recipient_user_id",recipient).is("acknowledged_at",null).select());return r.ok?{ok:true,data:undefined}:r;},notificationsFor:recipient=>state.notifications.filter(n=>n.recipientUserId===recipient).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),
 setUserAccessRole:async(id,role)=>{const r=await run(async()=>{const response=await fetch(`/api/admin/employees/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({accessRole:role})});const body=await response.json() as {error?:string};return {data:null,error:response.ok?null:{message:body.error??"Access role could not be updated."}};});return r.ok?{ok:true,data:undefined}:r;},setPermissionOverride:async(id,key,enabled)=>{const user=state.users.find(u=>u.id===id);const overrides={...user?.permissionOverrides,[key]:enabled};const r=await run(async()=>{const response=await fetch(`/api/admin/employees/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({permissionOverrides:overrides})});const body=await response.json() as {error?:string};return {data:null,error:response.ok?null:{message:body.error??"Permission could not be updated."}};});return r.ok?{ok:true,data:undefined}:r;},resetPermissionOverrides:async id=>{const r=await run(async()=>{const response=await fetch(`/api/admin/employees/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({permissionOverrides:{}})});const body=await response.json() as {error?:string};return {data:null,error:response.ok?null:{message:body.error??"Permission overrides could not be reset."}};});return r.ok?{ok:true,data:undefined}:r;},recordTimeEntry:type=>run(async()=>{const r=await createClient().rpc("record_time_event",{next_type:type});return {data:r.data?mapTimeEntry(r.data):null,error:r.error};}),createTimeRequest:async input=>{if(!currentUser)return failure({code:"unauthorized",message:"Sign in before submitting a request."});const r=await run(()=>createClient().from("time_requests").insert({user_id:currentUser.id,kind:input.kind,status:"pending",requested_for:input.requestedFor,hours:input.hours,reason:input.reason.trim(),target_entry_id:input.targetEntryId??null,requested_entry_type:input.requestedEntryType??null,requested_at:input.requestedAt??null}).select());return r.ok?{ok:true,data:undefined}:r;},reviewTimeRequest:async(id,decision)=>{const r=await run(()=>createClient().rpc("review_time_request",{request_id:id,decision}));return r.ok?{ok:true,data:undefined}:r;},
 uploadJobPhotos:async(jobId,files)=>{const blocked=guard();if(blocked)return blocked;try{for(const file of files){if(file.size>10*1024*1024)throw new Error(`${file.name} exceeds the 10 MB limit.`);if(!["image/jpeg","image/png","image/webp","image/heic"].includes(file.type))throw new Error(`${file.name} is not a supported image type.`);const path=`${jobId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const upload=await createClient().storage.from("job-photos").upload(path,file,{contentType:file.type});if(upload.error)throw upload.error;const record=await createClient().from("job_photos").insert({job_id:jobId,storage_path:path,uploaded_by_id:currentUser?.id}).select();if(record.error){await createClient().storage.from("job-photos").remove([path]);throw record.error;}}await refresh();return {ok:true,data:undefined};}catch(error){return failure(error);}},addJobNote:async(jobId,body)=>{const r=await run(()=>createClient().from("job_notes").insert({job_id:jobId,author_id:currentUser?.id,body:body.trim()}).select());return r.ok?{ok:true,data:undefined}:r;},
 saveCustomer:async(input,id)=>{const payload={name:input.name.trim(),phone:input.phone.trim(),email:input.email.trim(),address:input.address.trim(),customer_group:input.group??null,is_active:true};const r=await run(()=>id?createClient().from("customers").update(payload).eq("id",id).select():createClient().from("customers").insert(payload).select());return r.ok?{ok:true,data:undefined}:r;},deactivateCustomer:async id=>{const r=await run(()=>createClient().from("customers").update({is_active:false,deleted_at:new Date().toISOString()}).eq("id",id).select());return r.ok?{ok:true,data:undefined}:r;},
 saveTruck:async(input,id)=>{const payload={number:input.number.trim(),type:input.type,status:input.status,license_plate:input.licensePlate.trim(),assigned_driver_id:input.assignedDriverId,notes:input.notes};const r=await run(()=>id?createClient().from("trucks").update(payload).eq("id",id).select():createClient().from("trucks").insert(payload).select());return r.ok?{ok:true,data:undefined}:r;},saveDumpster:async(input,id)=>{const payload={code:input.code.trim(),size:input.size,status:input.status,type:input.type,air_tag_id:input.airTagId,current_location:input.currentLocation.trim(),notes:input.notes};const r=await run(()=>id?createClient().from("dumpsters").update(payload).eq("id",id).select():createClient().from("dumpsters").insert(payload).select());return r.ok?{ok:true,data:undefined}:r;}
 }),[canMutate,connectionMessage,connectionState,currentUser,guard,refresh,run,state]);return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useOperations(){const value=React.useContext(Context);if(!value)throw new Error("useOperations must be used inside OperationsProvider");return value;}
